//
#define MS_M1 1
#define MS_M2 3
#define MS_M3 5
//
#define MOM_M1 6
#define MOM_M2 8
#define MOM_M3 9
#define MOM_M4 13
#define MOM_M5 15
//xx},//itemname 
//itemid, maxstack, maxonmap
new ItemProbably[][3] = 
{
//****************************************************************************************************PODSTAWOWA SZANSAkij
//bronie 
{4, MS_M1, MOM_M5},
{22, MS_M1, MOM_M1},
//{28, MS_M1, MOM_M1},
{33, MS_M1, MOM_M1},
//ammo
{47, 20, MOM_M1},
{52, 10, MOM_M1},
{62, 10, MOM_M1},
//reszta
{53, MS_M3, MOM_M5},
{54, MS_M1, MOM_M3},
{69, MS_M1, MOM_M3},
{70, MS_M1, MOM_M3},
{71, MS_M1, MOM_M3},
{72, MS_M1, MOM_M3},
{73, MS_M1, MOM_M3},
{74, MS_M1, MOM_M3},
{75, MS_M1, MOM_M3},
{76, MS_M3, MOM_M4},
{77, MS_M3, MOM_M4},
{78, MS_M1, MOM_M2},
{82, MS_M1, MOM_M3},
{83, MS_M1, MOM_M3},
{84, MS_M1, MOM_M1},
{85, MS_M1, MOM_M1},
{86, MS_M1, MOM_M1},
{87, MS_M1, MOM_M1},
{88, MS_M1, MOM_M1},
{89, MS_M1, MOM_M1},
{90, MS_M1, MOM_M1},
{91, MS_M1, MOM_M1},
{92, MS_M1, MOM_M1},
{93, MS_M1, MOM_M1},
{94, MS_M1, MOM_M5},
{95, MS_M1, MOM_M2},
{98, MS_M1, MOM_M2},
{103, MS_M1, MOM_M2},
{106, MS_M1, MOM_M4},
{107, MS_M1, MOM_M1},
{112, MS_M1, MOM_M1},
{113, MS_M1, MOM_M1},
{114, MS_M1, MOM_M1},
{115, MS_M1, MOM_M1},
{116, MS_M1, MOM_M1},
{117, MS_M1, MOM_M1},
{118, MS_M1, MOM_M1},
{119, MS_M1, MOM_M1},
{120, MS_M1, MOM_M3},
{122, MS_M1, MOM_M3},
{133, MS_M1, MOM_M3},
{134, MS_M3, MOM_M5},
{135, MS_M2, MOM_M4},
{136, MS_M2, MOM_M2},
{143, MS_M1, MOM_M3},
{144, MS_M1, MOM_M3},
{147, MS_M1, MOM_M3},
{148, MS_M1, MOM_M1},
{149, MS_M1, MOM_M1},
{150, MS_M1, MOM_M1},
{159, MS_M1, MOM_M4},
{-1, -1, -1},//*************************************************************************PODKR犴ANE/ZR荅NICOWANIE
{137, 1, 350},//z這m
{139, 1, 200},//karton
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{139, 1, 200},//karton
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{139, 1, 200},//karton
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{139, 1, 200},//karton
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{139, 1, 200},//karton
{139, 1, 200},//karton
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{139, 1, 200},//karton
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{139, 1, 200},//karton
{139, 1, 200},//karton
{135, 1, 350},//zgnieciona pusza
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350},//z這m
{137, 1, 350}//z這m
};